title=terminal
font=JetBrainsMono Nerd Font:size=10
initial-window-size-chars=130x35
pad=3x0center

[colors]
background=282c34
foreground=abb2bf
flash=ebd09c

## Normal/regular colors (color palette 0-7)
regular0=181a1f  # black
regular1=e86671  # red
regular2=98c379  # green
regular3=d19a66  # orange
regular4=61afef  # blue
regular5=c678dd  # purple
regular6=56b6c2  # cyan
regular7=848b98  # white

## Bright colors (color palette 8-15)
bright0=181a1f   # black
bright1=e86671   # red
bright2=98c379   # green
bright3=d19a66   # orange
bright4=61afef   # blue
bright5=c678dd   # purple
bright6=56b6c2   # cyan
bright7=848b98   # white
